### PR TITLE
Fix removal of newlines after prettier-ignore

### PR DESCRIPTION
**Pull request by tylervz**
Fixes issue https://github.com/eemeli/prettier-plugin-properties/issues/12

The trailing newline is no longer getting removed for the key-value pair after a `# prettier-ignore`.

For nodes where `hasPrettierIgnore` is true, the `printIgnored` method was being called rather than the `printer` defined by `prettier-plugin-properties`. Consequently, a hardline was not being added after the key-value pair node was printed.
https://github.com/prettier/prettier/blob/d0b907620b5a59fb75829e1b46e0636a064adae6/src/main/ast-to-doc.js#L101-L102

### CODE REVIEW

**Comment by eemeli** [comment]
Odd that the GitHub CI action didn't trigger; will need to investigate.

Could you drop the dependency updates from this PR, unless they're required for the fix?

**Comment by tylervz** [comment]
Yes, I'll drop the dependency updates.

I don't have any personal experience with approving GitHub Actions to run on a PR from a public fork, but according to the documentation there ought to be a "Workflow(s) awaiting approval" section on Conversation tab of the PR where you can click "Approve and run".
https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks#about-workflow-runs-from-public-forks

**Comment by tylervz** [comment]
i think you might need to edit the GitHub Action workflow so it looks like this:
```yaml
name: Node.js

on:
  pull_request:
    branches: [master]
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]
  schedule:
    - cron: '0 12 * * 1' # At noon on Mondays
  workflow_dispatch:
```
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

After you edit the workflow, I'll probably need to rebase my `ignore` branch on the updated `master`.

**Comment by eemeli** [comment]
It looks like the action had gotten disabled due to a lack of activity, on account of its weekly cron schedule. I'd added that a while back to catch issues from Node.js & other env updates.

@tylervz If you push a commit to the branch (even an empty one) it'll hopefully refresh GitHub's UI so that I can approve a CI run.

**Review by eemeli — APPROVED** [review]
Looks like a sensible fix. There's some inefficiency that could be avoided by tracking the prettier-ignore state and relying on the order in which `print()` is called on nodes, but introducing such state is probably only worthwhile if someone complains about the operation being slow.

**Pull request merged**
